#!/bin/bash

# Help funtion
HELP() {
	echo ""
	echo "Usage:"
	echo "-d : Path to Drupal root Directory. No trailing slash"
	echo "-n : Name for this installation."
	echo ""
}
# end help funtion

#If no argument given, show HELP and exit
if [ $# -lt 1 ] ;then
HELP
exit 0
fi

ALIASFILE="/home/vagrant/.drush/aliases.drushrc.php"
TEMPLATE="/vagrant/app/scripts/templates/alias.template"
DOCROOT="/var/www"
DESTPATH=""
NAME=""
DOMAIN=""

while getopts d:n: option
do
  case "${option}"
  in
    d) DESTPATH=${OPTARG};;
    n) NAME=${OPTARG};;
  esac
done

# spacer
echo

# Check name
if [ -z "$NAME" ] ;then
  echo "ERROR: No Name. Please use -n to specify the name"
  exit 1
fi
DOMAIN=$NAME.localhost

if [ -z "$DESTPATH" ] ;then
  DESTPATH="$DOCROOT/$NAME"
fi


echo
echo "Updating Drush alias"
echo "NAME : $NAME"
echo "DOMAIN : $DOMAIN"
echo "DESTPATH : $DESTPATH"
echo

read -p "Are you sure? (y/N) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  echo
  echo "Not updating"
  echo
  exit 9
fi

echo
echo
echo "Updating"
echo


# Check drush alias directory exists
if [ ! -d "/home/vagrant/.drush" ]; then
  echo "Making .drush"
  mkdir /home/vagrant/.drush
fi


# Check alias file exists
if [ ! -f $ALIASFILE ]; then
  touch $ALIASFILE
  echo "<?php \n" > $ALIASFILE
  echo "?> \n" > $ALIASFILE
fi

echo "Updating alias file"

if ! grep -q "$NAME.localhost" $ALIASFILE; then
  head -n -1 $ALIASFILE > temp.txt


  cat "$TEMPLATE" >> temp.txt
  echo "" >> temp.txt

  sed -i "s|NAME|$NAME|g" temp.txt
  sed -i "s|ROOT|$DESTPATH|g" temp.txt
  sed -i "s|DOMAIN|$DOMAIN|g" temp.txt

  echo "?>" >> temp.txt

  mv $ALIASFILE $ALIASFILE.bak
  mv temp.txt $ALIASFILE

else
  echo "SKIPPING - domain already exists in alias file, pllease update manually"
fi



