#!/bin/bash

# Help funtion
HELP() {
	echo ""
	echo "Usage:"
	echo "-n : Name for this installation."
        echo "-d : Destination path"
        echo "-b : Branch"
	echo ""
}
# end help funtion

#If no argument given, show HELP and exit
if [ $# -lt 1 ] ;then
HELP
exit 0
fi

DESTPATH=""
NAME=""
REPO=""
DOCROOT="/var/www"
BRANCH="master"

while getopts n:d:b: option
do
   case "${option}"
   in
     d) DESTPATH=${OPTARG};;
     n) NAME=${OPTARG};;
     b) BRANCH=${OPTARG};;
   esac
done

# spacer
echo


# Check name
if [ -z "$NAME" ] ;then
	echo "ERROR: No Name. Please use -n to specify the name"
	exit 2
fi

REPO=~/repos/$NAME.git

if [ -z "$DESTPATH" ] ;then
	DESTPATH="$DOCROOT/$NAME"
fi


echo
echo "Installing new site"

echo "NAME : $NAME"
echo "REPO : $REPO"
echo "DESTPATH : $DESTPATH"
echo "BRANCH : $BRANCH"
echo

read -p "Are you sure? (y/N) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo
    echo "Not installing"
    echo
    exit 9
fi

echo
echo
echo "Beginning installation"
echo

if [ ! -d ~/repos ]; then
  mkdir ~/repos
fi

#check that docroot exists
if [ ! -d "$DOCROOT" ]; then
  echo "Making $DOCROOT"
  mkdir $DOCROOT
  sudo chown vagrant:www-data $DOCROOT
  sudo chmod 766 $DOCROOT
fi


# Create destination path and copy source
if [ ! -d "$DESTPATH" ]; then
  echo "Making $DESTPATH"
  mkdir $DESTPATH
  sudo chown vagrant:www-data $DESTPATH
  sudo chmod 766 $DESTPATH
fi


if [ ! -d "$REPO" ]; then
  echo "Making Repo"
  mkdir $REPO
  cd $REPO
  git init --bare
  touch hooks/post-receive

  echo "#!/bin/sh" >> hooks/post-receive
  echo "GIT_WORK_TREE=$DESTPATH git checkout -f $BRANCH" >> hooks/post-receive
  echo "sudo chown -R :www-data $DESTPATH" >> hooks/post-receive
  echo "sudo chmod -R 774 $DESTPATH" >> hooks/post-receive
  sudo chmod +x hooks/post-receive
fi


echo
echo "ALL DONE!"
echo
echo "Add remote to your git project : "
echo
echo "vagrant@vagrant:repos/$NAME.git"
echo


